chore: bump rust to 1.57
Required by env_logger v0.9.0:

error: package `os_str_bytes v6.3.0` cannot be built because
it requires rustc 1.57.0 or newer, while the currently active
rustc version is 1.56.1